### ISSUE TITLE
Time value change in calendar dialog

### ISSUE THREAD

**Issue by rakesh-roshan** [fooloomanzoo/datetime-picker#1]
In your demo, in case when I click on the element a popup opens to change date and time. Changing date is easy. But changing time is very difficult. I can not see what I am changing. When I type any value it takes some random value and closes the popup without asking me whether time is ok or not.

**Comment by fooloomanzoo** [comment]
Which browser are using?
the field in the ledt is for the hours (goes from 0 - 23, whats common where i am from), the middle is for the minutes (0 - 59) and same for seconds for the right input.
But you are right and and i will think about a easier user interface for the time and a reprsentation of the local time format.

**Comment by rakesh-roshan** [comment]
I am using Chrome version 57.0.2987.110 (64-bit). Even calendar ui does not work well. I keep on clicking a date but selected date value on UI does not change. And when I close the UI, it picks of the wrong value. I mean the value which I did not click.

**Comment by rakesh-roshan** [comment]
I am using on Mac OS

**Comment by fooloomanzoo** [comment]
I can not test Mac OS, because I don't have any related hardware, but I tested it again for Chrome Mobile Android and Windows and there it's working.  If you like, it would be nice, if you try to find the issue in the code, for what is not working for Chrome in Mac OS. What I also will try to do in next time to upgade to Polymer 2.0, but I can not help with Mac-related issues.
