### ISSUE TITLE
Future Issue

### ISSUE THREAD

**Issue by tuanphpvn** [fooloomanzoo/datetime-picker#12]
I already review the code. date-picker not actually depend on calendar-element. I think it will difficult to improve in the future. We should reimplement it. Also calendar-element should implement Polymer.IronOverlayBehavior.

**Comment by fooloomanzoo** [comment]
`date-picker` does depend on `calendar-element` by implementing [CalendarElementPattern](https://github.com/fooloomanzoo/datetime-picker/blob/master/calendar-element.html). Where would the calendar else coming from? 
Those elements all depend in a polymorphic way on each other and the templates are here combined in each other. The usage of those patterns makes it possible to combine different template strings, so that the needed static template getter is fullfilled when defining the customElement finally. Because `<datetime-picker>` and `<date-picker>` need the same template, too, it is a way to save redundancy. 

Also I tried to not use an inner calendar element in the template because I would have to repeat every attribute binding itself, and like that it is not necessary. 

The `calendar-element` itself also just mixins CalendarElementPattern, when being defined (it's on the bottom of the page of `calendar-element.html`). This technique is nowhere described like that, but I thought it makes sence, because I write some other polyfill pickers, too, like [<color-picker>](https://github.com/fooloomanzoo/color-picker/) and there I can also use that build-up.

There is `overlay-date-picker` that implements Polymer.IronOverlayBehavior, what does put it in an overlay or if you just need an calendar in an overlay there is [overlay-element](https://github.com/fooloomanzoo/input-picker-pattern/blob/master/overlay-element.html):

```html
<overlay-element opened="{{opened}}">
   <calendar-element date="{{date}}"></calendar-element>
</overlay-element>
```

The reason for doing it in first place just by css, is to keep it small, to can use the calendar-element separatly and keep it extendable.

**Comment by tuanphpvn** [comment]
Yes, It's special to implement this way, polymer supposed to simple. Your core is a little complicated. I hope you think again. This is just suggestion.

About me. I already implement in a new way. the element <date-picker> uses paper-input, iron-icon and it very simple.

Great work. BTW.
