### ISSUE TITLE
Broken on Safari 

### ISSUE THREAD

**Issue by binhbbui411** [fooloomanzoo/datetime-picker#15]
I am using Safari 11.0.1 and looks like the component is completely unusable there. 
- Clicking results in a huge delay. 
- Data-binding does not work.  

Here's my code https://codepen.io/SlashBunny/pen/EwbgdM?editors=1000

**Comment by fooloomanzoo** [comment]
@binhbbui411 I'm sorry, that I can not test for Safari, because I don't have a Mac available and Apple doesn't provide Safari for other systems.

But I noticed that you didn't test for the actual version `2.3.9`. Could you please try: https://codepen.io/fooloomanzoo/pen/jGpzxG

The **next version** will have a major change on how properties are set, so please check if the update in the next days would change that behavior in Safari.

**Comment by fooloomanzoo** [comment]
If it is working in Safari for the newest version 3.4.0, it would be nice of you to tell it, but otherwise I can not help you

**Comment by fooloomanzoo** [comment]
It might also have something to do, how the demos are transpiled by the server, that is provided by either webcomponents or github in this case. On the github pages and on the jsfiddle-examples there is no transpilation at all, so it is just raw, and so it might not work for safari. But thats a leak for Safari itself not being up to date and for Polymer being not compatible. Please have a look at the demos directly shown on the webcomponents-pages like [here](https://www.webcomponents.org/element/fooloomanzoo/datetime-picker/demo/demo/date-picker.html), that are tranpiled by the webcomponents-server. 
For being very slow it might also has something to do how it is transpiled and minified. For Chrome, Opera and Firefox-Browsers the performance is good on my system. The server integration might be very different for every use-case, but please have a look at [polymer-cli](https://github.com/Polymer/polymer-cli). But it would be nice, if you or someone on a Mac could please review and inspect some issues relating to the problems you found, because only that way it could become better.

**Comment by binhbbui411** [comment]
Hey I just have a test again with version 2.4.0 on Safari Tech Preview and it worked flawlessly. Good job! I am writing a review of datepicker components and we will also feature your component in our new directory which will be released soon so kudos to your fix!

**Comment by fooloomanzoo** [comment]
Good to hear. There will still be fixes, so everyone: please update
