### ISSUE TITLE
Uncaught TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by jjarrell56** [fooloomanzoo/datetime-picker#22]
I would appreciate a little help with getting Date-picker working in my Angular applications. It's not currently rendering and has the following errors at start up.

![image](https://user-images.githubusercontent.com/26254959/33444154-7e3c105e-d5c7-11e7-9354-d1a1b9cd53cd.png)

Angular, in index.html.  I am using a number of conventional Polymer 1x components.
```
 <link rel="import" href="assets/bower_components/datetime-picker/date-picker.html">
  <link rel="import" href="assets/bower_components/input-picker-pattern/overlay-element.html">
```

**Comment by fooloomanzoo** [comment]
Polymer 1 might not work with this element because you need to have the possibility to extend `Polymer.Element` like explained in [dev-guide](https://www.polymer-project.org/2.0/docs/devguide/custom-elements#extending-elements). But it should be safe for you to upgrade because polymer 2.x garantees backward compatibility to 1.x .
