### ISSUE TITLE
Errors on Handling range of dates

### ISSUE THREAD

**Issue by on4life** [fooloomanzoo/datetime-picker#31]
Hi, I tried to use range of dates picker but something want wrong. Could you please check this problem?

http://take.ms/qybt7

It happened when I choose "end day" less than "start day"

```
<date-picker class="begin" month="1" day="1" auto-confirm date="{{min}}" max="{{max}}" vertical-align="bottom"></date-picker>
<date-picker class="end" month="12" day="31" auto-confirm date="{{max}}" min="{{min}}" vertical-align="top"></date-picker>
```

**Comment by fooloomanzoo** [comment]
And what would you expect to happen, if you choose an earlier date for maximum than the minimum? 
The elements try to set then the values to their margins. 
Because you have two separated elements their is no way to mediate for them, if you don't include another binding.
But if min and max are set for one element then it would turn around min and max if they are in wrong order. This problem you are getting is only occurring because of your attempt to preset the date.
I would suggest that you include another hidden date-input as a mediator and bind its min and max attributes to the attributes of your pickers.

**Comment by fooloomanzoo** [comment]
And what would you expect to happen, if you choose an earlier date for maximum than the minimum? 
The elements try to set then the values to their margins. 
Because you have two separated elements their is no way to mediate for them, if you don't include another binding.
But if min and max are set for one element then it would turn around min and max if they are in wrong order. This problem you are getting is only occurring because of your attempt to preset the date.
I would suggest that you include another hidden date-input as a mediator and bind its min and max attributes to the attributes of your pickers.

**Comment by fooloomanzoo** [comment]
<date-picker auto-confirm month="12" day="31" date="{{min}}" max="[[max]]"></date-picker>
    <date-picker auto-confirm month="1" day="1" date="{{max}}" min="[[min]]"></date-picker>
    <date-input hidden max="{{max}}" min="{{min}}"></date-input>
