### ISSUE TITLE
Clicking outside non-native picker elements do not close them

### ISSUE THREAD

**Issue by lpellegr** [fooloomanzoo/datetime-picker#8]
Non-native pickers do not close when clicking outside them.

It would be really convenient to have this behavior to mimic what is available with native pickers. Also, such a behavior is more natural and in that case the top right closing button could be optional.

**Comment by fooloomanzoo** [comment]
This can usually be made by moving the element to the top layer and adding a scrim to the document, that can be clicked to cancel, like in polymer's iron-overlay-behavior. The problem there is the overhead you produce and my aim was to focus on using the native elements, no matter how they react and not trying to improve them.

**Comment by fooloomanzoo** [comment]
should be fully implemented: https://github.com/fooloomanzoo/datetime-picker/releases/tag/2.0.5

**Comment by lpellegr** [comment]
@fooloomanzoo  Thanks for the new release. Unfortunately, clicking outside non-native pickers do not close them. 

The issue appears when the component is included in my app but also with the demo page:

https://fooloomanzoo.github.io/datetime-picker/bower_components/datetime-picker/demo/

**Comment by fooloomanzoo** [comment]
look, I told you before why that would cause an overhead, because you need to create an overlay for doing that. Feel free to fork the element

**Comment by lpellegr** [comment]
@fooloomanzoo I was confused by your last comment that says:

> should be fully implemented:

Do you think that the overhead you speak about is really important? I mean, have you measured it? basic elements such as `iron-dropdown` use such an approach...

For sure I will fork, most probably as a new project.

**Comment by fooloomanzoo** [comment]
if you don't use `iron-overlay-behavior` in another context then is this is for shure just an extra what might not be necessary, if you just need an date-picker. The behavior itself has a size of circa 35kB, so it is larger than the size of this element by itself. Their is for shure a way to make it easier and not so complex like in the polymer implementation, but there is a lot to consider and to test creating a backdrop, because it should always guarantuee to be on the top layer, even if the element is deep nested. For that it might be easier to write a receiver overlay-extention that take over a node and adds it to its DOM by call rather than extending it the first place. I thought about it when writing this element but I decided to just place it using the position attribute. The main problem is that using to usual build process in polymer might ignore or move the optional loading of an element of that kind. Polymer 2.0 is not so fully mature that I could say what way is senseful to start. And my approach would always be to make this optional than implementing totally because it is too much extra code.

**Comment by fooloomanzoo** [comment]
@lpellegr I rewrote some code and introduced now an optional **overlay**. Like the polyfill-elements, they will be lazy loaded, so that if you bundle your project, they might are missing. For that I wrote a a possible solution in the `README.md`. Also there is a new [demo-page](https://fooloomanzoo.github.io/datetime-picker/components/datetime-picker/#/elements/datetime-picker/demos/demo/datetime-picker.html). I hope, this could help you.
